// Code generated by go-bindata.
// sources:
// static/config/mowos-agent.yml
// static/config/mowos-monitor.yml
// static/web/css/style.css
// static/web/css/vendor/semantic.min.css
// static/web/index.html
// static/web/js/app.js
// static/web/js/vendor/vue-router.js
// static/web/js/vendor/vue.js
// DO NOT EDIT!

package mowos

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// configMowosAgentYml reads file data from disk. It returns an error on failure.
func configMowosAgentYml() (*asset, error) {
	path := "/vagrant/gopath/src/github.com/mbndr/mowos/static/config/mowos-agent.yml"
	name := "config/mowos-agent.yml"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// configMowosMonitorYml reads file data from disk. It returns an error on failure.
func configMowosMonitorYml() (*asset, error) {
	path := "/vagrant/gopath/src/github.com/mbndr/mowos/static/config/mowos-monitor.yml"
	name := "config/mowos-monitor.yml"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// webCssStyleCss reads file data from disk. It returns an error on failure.
func webCssStyleCss() (*asset, error) {
	path := "/vagrant/gopath/src/github.com/mbndr/mowos/static/web/css/style.css"
	name := "web/css/style.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// webCssVendorSemanticMinCss reads file data from disk. It returns an error on failure.
func webCssVendorSemanticMinCss() (*asset, error) {
	path := "/vagrant/gopath/src/github.com/mbndr/mowos/static/web/css/vendor/semantic.min.css"
	name := "web/css/vendor/semantic.min.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// webIndexHtml reads file data from disk. It returns an error on failure.
func webIndexHtml() (*asset, error) {
	path := "/vagrant/gopath/src/github.com/mbndr/mowos/static/web/index.html"
	name := "web/index.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// webJsAppJs reads file data from disk. It returns an error on failure.
func webJsAppJs() (*asset, error) {
	path := "/vagrant/gopath/src/github.com/mbndr/mowos/static/web/js/app.js"
	name := "web/js/app.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// webJsVendorVueRouterJs reads file data from disk. It returns an error on failure.
func webJsVendorVueRouterJs() (*asset, error) {
	path := "/vagrant/gopath/src/github.com/mbndr/mowos/static/web/js/vendor/vue-router.js"
	name := "web/js/vendor/vue-router.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// webJsVendorVueJs reads file data from disk. It returns an error on failure.
func webJsVendorVueJs() (*asset, error) {
	path := "/vagrant/gopath/src/github.com/mbndr/mowos/static/web/js/vendor/vue.js"
	name := "web/js/vendor/vue.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"config/mowos-agent.yml":          configMowosAgentYml,
	"config/mowos-monitor.yml":        configMowosMonitorYml,
	"web/css/style.css":               webCssStyleCss,
	"web/css/vendor/semantic.min.css": webCssVendorSemanticMinCss,
	"web/index.html":                  webIndexHtml,
	"web/js/app.js":                   webJsAppJs,
	"web/js/vendor/vue-router.js":     webJsVendorVueRouterJs,
	"web/js/vendor/vue.js":            webJsVendorVueJs,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"config": &bintree{nil, map[string]*bintree{
		"mowos-agent.yml":   &bintree{configMowosAgentYml, map[string]*bintree{}},
		"mowos-monitor.yml": &bintree{configMowosMonitorYml, map[string]*bintree{}},
	}},
	"web": &bintree{nil, map[string]*bintree{
		"css": &bintree{nil, map[string]*bintree{
			"style.css": &bintree{webCssStyleCss, map[string]*bintree{}},
			"vendor": &bintree{nil, map[string]*bintree{
				"semantic.min.css": &bintree{webCssVendorSemanticMinCss, map[string]*bintree{}},
			}},
		}},
		"index.html": &bintree{webIndexHtml, map[string]*bintree{}},
		"js": &bintree{nil, map[string]*bintree{
			"app.js": &bintree{webJsAppJs, map[string]*bintree{}},
			"vendor": &bintree{nil, map[string]*bintree{
				"vue-router.js": &bintree{webJsVendorVueRouterJs, map[string]*bintree{}},
				"vue.js":        &bintree{webJsVendorVueJs, map[string]*bintree{}},
			}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
