// Code generated by go-bindata.
// sources:
// static/config/mowos-agent.yml
// static/config/mowos-monitor.yml
// DO NOT EDIT!

package mowos

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _configMowosAgentYml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x8c\x8d\x41\x0e\xc2\x20\x10\x45\xf7\x9c\xe2\x67\xf6\x18\xba\x70\xc3\x01\xbc\x80\x27\x40\x33\x35\x13\x01\x09\x8c\x36\xbd\xbd\xc1\xda\xa8\x5d\x19\x76\xff\xf1\xde\x84\x0b\x67\xf5\x06\x00\xa2\x34\xe5\x6c\xa5\x78\x90\xdb\xbd\x1e\x7d\x83\x72\xab\xea\x41\xc3\xe0\xf6\x8e\x8c\x11\xe5\xd4\x16\xd3\x42\xe7\xc2\x1e\xd4\xb8\x3e\xe4\xcc\x8b\x06\x5c\x79\xee\x63\x48\xa7\x60\x3b\xe2\xba\x92\x1c\x52\xff\x7f\xec\x08\xbf\xe8\xdd\x58\x45\x32\x7f\x9c\x18\xa5\xf2\x14\x62\xdc\xe4\x0f\x9b\xf9\x93\xbe\x8f\x13\x99\x67\x00\x00\x00\xff\xff\x02\x42\x32\xcd\xfc\x00\x00\x00")

func configMowosAgentYmlBytes() ([]byte, error) {
	return bindataRead(
		_configMowosAgentYml,
		"config/mowos-agent.yml",
	)
}

func configMowosAgentYml() (*asset, error) {
	bytes, err := configMowosAgentYmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "config/mowos-agent.yml", size: 252, mode: os.FileMode(436), modTime: time.Unix(1506261598, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _configMowosMonitorYml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x4c\xce\x41\xaa\xc2\x30\x10\xc6\xf1\x7d\x4e\xf1\x31\xab\xf7\x16\x0d\x13\x51\x2c\x39\x81\xee\xc4\x9e\x20\xea\x48\x03\x4d\xa6\x24\xc1\xf3\x8b\xc4\x82\xdb\x99\xef\x0f\xbf\xa4\x39\x36\x2d\xde\x00\xc0\x12\x6b\x93\x3c\xc4\xd5\x83\xdc\xee\x68\xd9\xb2\x75\xf4\xfb\x5a\xb5\x34\x0f\x1a\x79\x64\x32\x66\xd6\xda\x6a\x4f\x07\xe4\x90\xc4\x83\x4e\x9a\xa4\x4a\x79\x49\xe9\x21\xf0\x90\x7a\x2f\x71\x6d\x51\xb3\x07\x4d\x29\x2c\x0b\x66\x4d\x82\x3e\xc3\xdf\xf5\x72\xfe\xc7\x53\x0b\xa6\x90\x6e\x61\xcb\xba\xe2\x43\xd8\xb3\x75\x6e\x3b\x7f\x05\xce\xf1\x81\xc9\xbc\x03\x00\x00\xff\xff\x5a\x9d\xda\x81\xbf\x00\x00\x00")

func configMowosMonitorYmlBytes() ([]byte, error) {
	return bindataRead(
		_configMowosMonitorYml,
		"config/mowos-monitor.yml",
	)
}

func configMowosMonitorYml() (*asset, error) {
	bytes, err := configMowosMonitorYmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "config/mowos-monitor.yml", size: 191, mode: os.FileMode(436), modTime: time.Unix(1506277811, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"config/mowos-agent.yml":   configMowosAgentYml,
	"config/mowos-monitor.yml": configMowosMonitorYml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"config": &bintree{nil, map[string]*bintree{
		"mowos-agent.yml":   &bintree{configMowosAgentYml, map[string]*bintree{}},
		"mowos-monitor.yml": &bintree{configMowosMonitorYml, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
