agent:
    listen-ip: "0.0.0.0"
    listen-port: "11050"

items:
    - type: "service"
      key: "samba-server"
      name: "Samba server"
      service: "samba"

    - type: "service"
      key: "firewall"
      name: "Firewall"
      service: "ufw"
